{ ... }:
{
  environment.etc."xdg/hypr/hyprland.conf".text = ''
    autogenerated = 0

    $mod = SUPER

    exec-once = hyprpanel

    bind = $mod, Return, exec, ghostty
    bind = $mod, D, exec, fuzzel
    bind = $mod, Q, killactive
    bind = $mod SHIFT, M, exit

    bind = $mod, H, movefocus, l
    bind = $mod, L, movefocus, r
    bind = $mod, K, movefocus, u
    bind = $mod, J, movefocus, d
  '';
}
